### ISSUE TITLE
zombies.onplay causes crash

### ISSUE THREAD

**Issue by lothar243** [lothar243/Survivors-Of-The-Apocalypse#5]
zombies and raiders both have concurrent modification exceptions... you're changing the arraylist as you're iterating through it

04-29 06:45:07.949 20791-20791/edu.umt.csdept.survivorsoftheapocalypse E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: edu.umt.csdept.survivorsoftheapocalypse, PID: 20791
                                                                                         java.util.ConcurrentModificationException
                                                                                             at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.Zombies.onPlay(PlayCardImpl.java:109)
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.Zombies.onAquire(PlayCardImpl.java:101)
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.GameState.drawPlayCard(GameState.java:191)
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.InGameActivity.drawCard(InGameActivity.java:255)
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.InGameActivity$2.onClick(InGameActivity.java:130)
                                                                                             at android.view.View.performClick(View.java:5697)
                                                                                             at android.widget.TextView.performClick(TextView.java:10814)
                                                                                             at android.view.View$PerformClick.run(View.java:22526)
                                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by lothar243** [comment]
The game no longer crashes on drawing them, but now they appear to do nothing. All people seem to survive, whether they are behind walls or not

**Comment by BrianTrethewey** [comment]
should now kill people correctly
