### ISSUE TITLE
Null point exception when the deck runs out

### ISSUE THREAD

**Issue by lothar243** [lothar243/Survivors-Of-The-Apocalypse#6]
On drawing the 28th card, the game crashes with a null pointer exception

java.lang.NullPointerException: Attempt to invoke interface method 'void edu.umt.csdept.survivorsoftheapocalypse.Card.onAquire(edu.umt.csdept.survivorsoftheapocalypse.GameState)' on a null object reference
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.GameState.drawPlayCard(GameState.java:195)
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.InGameActivity.drawCard(InGameActivity.java:255)
                                                                                             at edu.umt.csdept.survivorsoftheapocalypse.InGameActivity$2.onClick(InGameActivity.java:130)
                                                                                             at android.view.View.performClick(View.java:5697)
                                                                                             at android.widget.TextView.performClick(TextView.java:10814)
                                                                                             at android.view.View$PerformClick.run(View.java:22526)
                                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by BrianTrethewey** [comment]
Fixed deck now refreshes
